### ISSUE TITLE
Cross Post works the other way round (1:1)

### ISSUE THREAD

**Issue by redditindiaspeaks** [impshum/Reddit-Pinned-Sniper#2]
The script is supposed to Cross Post from A to B,C

```
main_subreddit = A
target_subreddits = B, C
```

But when I run the script, it cross posts from B to A and C

And if I pick just one Sub and interchange the "Main" and "Target" sub names, it works fine.

Eg:

I want to cross post from A to B

I set B as Main even though its my target sub

main_subreddit = B
target_subreddits = A

Could you please check ?

Also when I ran it as is, like you have mentioned in ReadMe,
I get the below errors

λ python run.py
```
['indiaspeaks']
Traceback (most recent call last):
  File "run.py", line 88, in <module>
    main()
  File "run.py", line 76, in main
    sniper(reddit, main_subreddit, target_subreddits,
  File "run.py", line 46, in sniper
    submission.crosspost(
  File "C:\Python3.8\lib\site-packages\praw\models\reddit\submission.py", line 721, in crosspost
    return self._reddit.post(API_PATH["submit"], data=data)
  File "C:\Python3.8\lib\site-packages\praw\reddit.py", line 632, in post
    return self._objectify_request(
  File "C:\Python3.8\lib\site-packages\praw\reddit.py", line 572, in _objectify_request
    return self._objector.objectify(
  File "C:\Python3.8\lib\site-packages\praw\objector.py", line 164, in objectify
    raise RedditAPIException(errors)
praw.exceptions.RedditAPIException: SUBREDDIT_NOEXIST: "that subreddit doesn't exist" on field 'sr'
```

**Comment by impshum** [comment]
```main_subreddit``` is the sub you want to post to. ```target_subreddits ``` are the subs you want to get data from.

And this hasn't got anything to do with me.

> that subreddit doesn't exist
